version: '3.8'
name: chinook
services:

  #----------------------------------------------------------------------------
  # MySQL Container
  # https://hub.docker.com/_/mysql
  # Commands:
  #   mysql -u chinook -p Chinook
  #----------------------------------------------------------------------------
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: chinook
      MYSQL_PASSWORD: chinook
      MYSQL_ROOT_PASSWORD: chinook
      MYSQL_DATABASE: Chinook_AutoIncrement
    ports:
      - "3306:3306"
    volumes:
      - ./ChinookDatabase/Chinook_MySql_AutoIncrementPKs.sql:/docker-entrypoint-initdb.d/Chinook_MySql_AutoIncrementPKs.sql

  #----------------------------------------------------------------------------
  # Oracle Container
  # https://container-registry.oracle.com/ords/ocr/ba/database/express
  # https://hub.docker.com/r/gvenzl/oracle-xe (Apple M chips)
  # Commands:
  #   sqlplus -S / as sysdba @ /container-entrypoint-initdb.d/create_database.sql
  #----------------------------------------------------------------------------